export interface PseoPageConfig {
  slug: string;
  category: "reels" | "story" | "photo" | "audio" | "profile";
  h1: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
}

export const REELSER_PSEO_PAGES: Record<string, PseoPageConfig> = {
  "instagram-reels-download": {
    slug: "instagram-reels-download",
    category: "reels",
    h1: "Instagram Reels Downloader",
    metaTitle: "Instagram Reels Downloader - Reelser",
    metaDescription: "Download Instagram Reels in source quality MP4 with original crystal-clear audio. Fast, free, and no watermark.",
    keywords: ["instagram","ig","instagram reels download","reels download","save insta","reels downloader","download instagram reels","m instagram","for instagram","cara download reels ig","download reels instagram","download reels","instagram reels download app","reels video download","save instagram reels","app to download instagram reels","save reels ig","download ig reels","save reels to camera roll","download reels from instagram","instagram reels download apk","instagram reels video download","cara save reels ig","tiktok reels download","reels download app","save reels","download reels on instagram","instagram reels video download in gallery","save reels from instagram","apps to download instagram reels"],
  },
  "download-instagram-reels": {
    slug: "download-instagram-reels",
    category: "reels",
    h1: "Instagram Reels Downloader",
    metaTitle: "Instagram Reels Downloader - Reelser",
    metaDescription: "Download Instagram Reels in source quality MP4 with original crystal-clear audio. Fast, free, and no watermark.",
    keywords: ["instagram","ig","instagram reels download","reels download","save insta","reels downloader","download instagram reels","m instagram","for instagram","cara download reels ig","download reels instagram","download reels","instagram reels download app","reels video download","save instagram reels","app to download instagram reels","save reels ig","download ig reels","save reels to camera roll","download reels from instagram","instagram reels download apk","instagram reels video download","cara save reels ig","tiktok reels download","reels download app","save reels","download reels on instagram","instagram reels video download in gallery","save reels from instagram","apps to download instagram reels"],
  },
  "reels-downloader": {
    slug: "reels-downloader",
    category: "reels",
    h1: "Instagram Reels Downloader",
    metaTitle: "Instagram Reels Downloader - Reelser",
    metaDescription: "Download Instagram Reels in source quality MP4 with original crystal-clear audio. Fast, free, and no watermark.",
    keywords: ["instagram","ig","instagram reels download","reels download","save insta","reels downloader","download instagram reels","m instagram","for instagram","cara download reels ig","download reels instagram","download reels","instagram reels download app","reels video download","save instagram reels","app to download instagram reels","save reels ig","download ig reels","save reels to camera roll","download reels from instagram","instagram reels download apk","instagram reels video download","cara save reels ig","tiktok reels download","reels download app","save reels","download reels on instagram","instagram reels video download in gallery","save reels from instagram","apps to download instagram reels"],
  },
  "save-instagram-reels": {
    slug: "save-instagram-reels",
    category: "reels",
    h1: "Instagram Reels Downloader",
    metaTitle: "Instagram Reels Downloader - Reelser",
    metaDescription: "Download Instagram Reels in source quality MP4 with original crystal-clear audio. Fast, free, and no watermark.",
    keywords: ["instagram","ig","instagram reels download","reels download","save insta","reels downloader","download instagram reels","m instagram","for instagram","cara download reels ig","download reels instagram","download reels","instagram reels download app","reels video download","save instagram reels","app to download instagram reels","save reels ig","download ig reels","save reels to camera roll","download reels from instagram","instagram reels download apk","instagram reels video download","cara save reels ig","tiktok reels download","reels download app","save reels","download reels on instagram","instagram reels video download in gallery","save reels from instagram","apps to download instagram reels"],
  },
  "instagram-reels-video-download": {
    slug: "instagram-reels-video-download",
    category: "reels",
    h1: "Instagram Reels Downloader",
    metaTitle: "Instagram Reels Downloader - Reelser",
    metaDescription: "Download Instagram Reels in source quality MP4 with original crystal-clear audio. Fast, free, and no watermark.",
    keywords: ["instagram","ig","instagram reels download","reels download","save insta","reels downloader","download instagram reels","m instagram","for instagram","cara download reels ig","download reels instagram","download reels","instagram reels download app","reels video download","save instagram reels","app to download instagram reels","save reels ig","download ig reels","save reels to camera roll","download reels from instagram","instagram reels download apk","instagram reels video download","cara save reels ig","tiktok reels download","reels download app","save reels","download reels on instagram","instagram reels video download in gallery","save reels from instagram","apps to download instagram reels"],
  },
  "instagram-reels-without-watermark": {
    slug: "instagram-reels-without-watermark",
    category: "reels",
    h1: "Instagram Downloader Without Watermark",
    metaTitle: "Instagram Downloader Without Watermark - Reelser",
    metaDescription: "Save Instagram Reels and videos cleanly without any watermark or logo in source quality.",
    keywords: ["instagram","instagram video download","ig","instagram video","reels download","download video ig","download instagram reels","download video ig tanpa watermark","save reel without watermark","download ins","download instagram video without watermark","download video ig tanpa watermark 2021","download video ig tanpa watermark 2022","gram video download","instagram reels download no watermark","instagram reels without watermark","instagram video download no watermark","instagram video without watermark","instagram video without watermark download"],
  },
  "instagram-reels-download-online": {
    slug: "instagram-reels-download-online",
    category: "reels",
    h1: "Instagram Reels Downloader",
    metaTitle: "Instagram Reels Downloader - Reelser",
    metaDescription: "Download Instagram Reels in source quality MP4 with original crystal-clear audio. Fast, free, and no watermark.",
    keywords: ["instagram","ig","instagram reels download","reels download","save insta","reels downloader","download instagram reels","m instagram","for instagram","cara download reels ig","download reels instagram","download reels","instagram reels download app","reels video download","save instagram reels","app to download instagram reels","save reels ig","download ig reels","save reels to camera roll","download reels from instagram","instagram reels download apk","instagram reels video download","cara save reels ig","tiktok reels download","reels download app","save reels","download reels on instagram","instagram reels video download in gallery","save reels from instagram","apps to download instagram reels"],
  },
  "reels-download-hd": {
    slug: "reels-download-hd",
    category: "reels",
    h1: "Instagram Reels Downloader",
    metaTitle: "Instagram Reels Downloader - Reelser",
    metaDescription: "Download Instagram Reels in source quality MP4 with original crystal-clear audio. Fast, free, and no watermark.",
    keywords: ["instagram","ig","instagram reels download","reels download","save insta","reels downloader","download instagram reels","m instagram","for instagram","cara download reels ig","download reels instagram","download reels","instagram reels download app","reels video download","save instagram reels","app to download instagram reels","save reels ig","download ig reels","save reels to camera roll","download reels from instagram","instagram reels download apk","instagram reels video download","cara save reels ig","tiktok reels download","reels download app","save reels","download reels on instagram","instagram reels video download in gallery","save reels from instagram","apps to download instagram reels"],
  },
  "download-reels-by-link": {
    slug: "download-reels-by-link",
    category: "reels",
    h1: "Instagram Reels Downloader",
    metaTitle: "Instagram Reels Downloader - Reelser",
    metaDescription: "Download Instagram Reels in source quality MP4 with original crystal-clear audio. Fast, free, and no watermark.",
    keywords: ["instagram","ig","instagram reels download","reels download","save insta","reels downloader","download instagram reels","m instagram","for instagram","cara download reels ig","download reels instagram","download reels","instagram reels download app","reels video download","save instagram reels","app to download instagram reels","save reels ig","download ig reels","save reels to camera roll","download reels from instagram","instagram reels download apk","instagram reels video download","cara save reels ig","tiktok reels download","reels download app","save reels","download reels on instagram","instagram reels video download in gallery","save reels from instagram","apps to download instagram reels"],
  },
  "instagram-video-download": {
    slug: "instagram-video-download",
    category: "reels",
    h1: "Instagram Video Downloader",
    metaTitle: "Instagram Video Downloader - Reelser",
    metaDescription: "Free online Instagram video downloader. Download Instagram videos in high-definition MP4 without watermark.",
    keywords: ["instagram","instagram video download","ig","instagram video","save insta","download video ig","save video from instagram","m instagram","for instagram","instagram video download app","instagram co","app to save instagram videos","save instagram videos to camera roll","instagram c","best app to download instagram videos","best instagram video downloader","save video ig","save instagram video to iphone","instagram video downloader apk","instagram video download mp4","instagram video downloader iphone","instagram video downloader online","save instagram video to phone","download video from instagram to iphone","download video ig tanpa watermark","download video instagram reels","download video instagram story","instagram video converter","private instagram video downloader","best instagram video downloader for iphone"],
  },
  "download-instagram-video": {
    slug: "download-instagram-video",
    category: "reels",
    h1: "Instagram Video Downloader",
    metaTitle: "Instagram Video Downloader - Reelser",
    metaDescription: "Free online Instagram video downloader. Download Instagram videos in high-definition MP4 without watermark.",
    keywords: ["instagram","instagram video download","ig","instagram video","save insta","download video ig","save video from instagram","m instagram","for instagram","instagram video download app","instagram co","app to save instagram videos","save instagram videos to camera roll","instagram c","best app to download instagram videos","best instagram video downloader","save video ig","save instagram video to iphone","instagram video downloader apk","instagram video download mp4","instagram video downloader iphone","instagram video downloader online","save instagram video to phone","download video from instagram to iphone","download video ig tanpa watermark","download video instagram reels","download video instagram story","instagram video converter","private instagram video downloader","best instagram video downloader for iphone"],
  },
  "instagram-video-downloader": {
    slug: "instagram-video-downloader",
    category: "reels",
    h1: "Instagram Video Downloader",
    metaTitle: "Instagram Video Downloader - Reelser",
    metaDescription: "Free online Instagram video downloader. Download Instagram videos in high-definition MP4 without watermark.",
    keywords: ["instagram","instagram video download","ig","instagram video","save insta","download video ig","save video from instagram","m instagram","for instagram","instagram video download app","instagram co","app to save instagram videos","save instagram videos to camera roll","instagram c","best app to download instagram videos","best instagram video downloader","save video ig","save instagram video to iphone","instagram video downloader apk","instagram video download mp4","instagram video downloader iphone","instagram video downloader online","save instagram video to phone","download video from instagram to iphone","download video ig tanpa watermark","download video instagram reels","download video instagram story","instagram video converter","private instagram video downloader","best instagram video downloader for iphone"],
  },
  "save-instagram-video": {
    slug: "save-instagram-video",
    category: "reels",
    h1: "Instagram Video Downloader",
    metaTitle: "Instagram Video Downloader - Reelser",
    metaDescription: "Free online Instagram video downloader. Download Instagram videos in high-definition MP4 without watermark.",
    keywords: ["instagram","instagram video download","ig","instagram video","save insta","download video ig","save video from instagram","m instagram","for instagram","instagram video download app","instagram co","app to save instagram videos","save instagram videos to camera roll","instagram c","best app to download instagram videos","best instagram video downloader","save video ig","save instagram video to iphone","instagram video downloader apk","instagram video download mp4","instagram video downloader iphone","instagram video downloader online","save instagram video to phone","download video from instagram to iphone","download video ig tanpa watermark","download video instagram reels","download video instagram story","instagram video converter","private instagram video downloader","best instagram video downloader for iphone"],
  },
  "instagram-video-download-hd": {
    slug: "instagram-video-download-hd",
    category: "reels",
    h1: "Instagram Video Downloader",
    metaTitle: "Instagram Video Downloader - Reelser",
    metaDescription: "Free online Instagram video downloader. Download Instagram videos in high-definition MP4 without watermark.",
    keywords: ["instagram","instagram video download","ig","instagram video","save insta","download video ig","save video from instagram","m instagram","for instagram","instagram video download app","instagram co","app to save instagram videos","save instagram videos to camera roll","instagram c","best app to download instagram videos","best instagram video downloader","save video ig","save instagram video to iphone","instagram video downloader apk","instagram video download mp4","instagram video downloader iphone","instagram video downloader online","save instagram video to phone","download video from instagram to iphone","download video ig tanpa watermark","download video instagram reels","download video instagram story","instagram video converter","private instagram video downloader","best instagram video downloader for iphone"],
  },
  "instagram-video-without-watermark": {
    slug: "instagram-video-without-watermark",
    category: "reels",
    h1: "Instagram Downloader Without Watermark",
    metaTitle: "Instagram Downloader Without Watermark - Reelser",
    metaDescription: "Save Instagram Reels and videos cleanly without any watermark or logo in source quality.",
    keywords: ["instagram","instagram video download","ig","instagram video","reels download","download video ig","download instagram reels","download video ig tanpa watermark","save reel without watermark","download ins","download instagram video without watermark","download video ig tanpa watermark 2021","download video ig tanpa watermark 2022","gram video download","instagram reels download no watermark","instagram reels without watermark","instagram video download no watermark","instagram video without watermark","instagram video without watermark download"],
  },
  "instagram-to-mp4": {
    slug: "instagram-to-mp4",
    category: "reels",
    h1: "Instagram to MP4 Converter",
    metaTitle: "Instagram to MP4 Converter - Reelser",
    metaDescription: "Convert Instagram video and reel links to high-definition MP4 online for free. Works on iPhone, Android, and PC.",
    keywords: ["instagram","ig","instagram video","instagram to mp4","convert from instagram to mp4","convert ig to mp4","convert instagram link to mp4","convert instagram to mp4 safe","download from instagram to mp4","download instagram video to mp4","download video instagram to mp4","from instagram to mp4","instagram link to mp4 converter","instagram to mp4 1080p","instagram to mp4 app","instagram to mp4 converter download","instagram to mp4 converter online","instagram to mp4 converter private","instagram to mp4 converter y2mate","instagram to mp4 high quality","instagram to mp4 online","instagram to mp4 private","instagram to mp4 video converter","instagram to mp4 video download","instagram to mp4 y2mate","instagram video to mp4 converter","instagram video to mp4 converter online","instagram video to mp4 download","instagram video to mp4 hd"],
  },
  "download-instagram-video-by-link": {
    slug: "download-instagram-video-by-link",
    category: "reels",
    h1: "Instagram Video Downloader",
    metaTitle: "Instagram Video Downloader - Reelser",
    metaDescription: "Free online Instagram video downloader. Download Instagram videos in high-definition MP4 without watermark.",
    keywords: ["instagram","instagram video download","ig","instagram video","save insta","download video ig","save video from instagram","m instagram","for instagram","instagram video download app","instagram co","app to save instagram videos","save instagram videos to camera roll","instagram c","best app to download instagram videos","best instagram video downloader","save video ig","save instagram video to iphone","instagram video downloader apk","instagram video download mp4","instagram video downloader iphone","instagram video downloader online","save instagram video to phone","download video from instagram to iphone","download video ig tanpa watermark","download video instagram reels","download video instagram story","instagram video converter","private instagram video downloader","best instagram video downloader for iphone"],
  },
  "story-saver": {
    slug: "story-saver",
    category: "story",
    h1: "Instagram Story & Highlights Saver",
    metaTitle: "Instagram Story & Highlights Saver - Reelser",
    metaDescription: "Download Instagram Stories and Highlights anonymously in original high quality before they expire.",
    keywords: ["instagram","ig","story saver","instagram story download","save insta","storiesig","ig app","instagram story download app","instagram story saver","instagram story download apk","download ig story","story saver instagram","storiesig app","instagram story saver app","story saver app","download story ig private","best instagram story downloader","instagram story saver apk","story saver instagram app","story saver net","story saver apk","story saver instagram apk download","ig view","instagram story download 1080p","instagram stalker story viewer","instagram highlights download","instagram story download free app","cara download story ig orang lain","save instagram story with music","download highlight instagram"],
  },
  "instagram-story-download": {
    slug: "instagram-story-download",
    category: "story",
    h1: "Instagram Story & Highlights Saver",
    metaTitle: "Instagram Story & Highlights Saver - Reelser",
    metaDescription: "Download Instagram Stories and Highlights anonymously in original high quality before they expire.",
    keywords: ["instagram","ig","story saver","instagram story download","save insta","storiesig","ig app","instagram story download app","instagram story saver","instagram story download apk","download ig story","story saver instagram","storiesig app","instagram story saver app","story saver app","download story ig private","best instagram story downloader","instagram story saver apk","story saver instagram app","story saver net","story saver apk","story saver instagram apk download","ig view","instagram story download 1080p","instagram stalker story viewer","instagram highlights download","instagram story download free app","cara download story ig orang lain","save instagram story with music","download highlight instagram"],
  },
  "storiesig-viewer": {
    slug: "storiesig-viewer",
    category: "story",
    h1: "Instagram Story & Highlights Saver",
    metaTitle: "Instagram Story & Highlights Saver - Reelser",
    metaDescription: "Download Instagram Stories and Highlights anonymously in original high quality before they expire.",
    keywords: ["instagram","ig","story saver","instagram story download","save insta","storiesig","ig app","instagram story download app","instagram story saver","instagram story download apk","download ig story","story saver instagram","storiesig app","instagram story saver app","story saver app","download story ig private","best instagram story downloader","instagram story saver apk","story saver instagram app","story saver net","story saver apk","story saver instagram apk download","ig view","instagram story download 1080p","instagram stalker story viewer","instagram highlights download","instagram story download free app","cara download story ig orang lain","save instagram story with music","download highlight instagram"],
  },
  "instagram-highlights-download": {
    slug: "instagram-highlights-download",
    category: "story",
    h1: "Instagram Story & Highlights Saver",
    metaTitle: "Instagram Story & Highlights Saver - Reelser",
    metaDescription: "Download Instagram Stories and Highlights anonymously in original high quality before they expire.",
    keywords: ["instagram","ig","story saver","instagram story download","save insta","storiesig","ig app","instagram story download app","instagram story saver","instagram story download apk","download ig story","story saver instagram","storiesig app","instagram story saver app","story saver app","download story ig private","best instagram story downloader","instagram story saver apk","story saver instagram app","story saver net","story saver apk","story saver instagram apk download","ig view","instagram story download 1080p","instagram stalker story viewer","instagram highlights download","instagram story download free app","cara download story ig orang lain","save instagram story with music","download highlight instagram"],
  },
  "anonymous-instagram-story-viewer": {
    slug: "anonymous-instagram-story-viewer",
    category: "story",
    h1: "Instagram Story & Highlights Saver",
    metaTitle: "Instagram Story & Highlights Saver - Reelser",
    metaDescription: "Download Instagram Stories and Highlights anonymously in original high quality before they expire.",
    keywords: ["instagram","ig","story saver","instagram story download","save insta","storiesig","ig app","instagram story download app","instagram story saver","instagram story download apk","download ig story","story saver instagram","storiesig app","instagram story saver app","story saver app","download story ig private","best instagram story downloader","instagram story saver apk","story saver instagram app","story saver net","story saver apk","story saver instagram apk download","ig view","instagram story download 1080p","instagram stalker story viewer","instagram highlights download","instagram story download free app","cara download story ig orang lain","save instagram story with music","download highlight instagram"],
  },
  "instagram-story-download-with-music": {
    slug: "instagram-story-download-with-music",
    category: "story",
    h1: "Instagram Story & Highlights Saver",
    metaTitle: "Instagram Story & Highlights Saver - Reelser",
    metaDescription: "Download Instagram Stories and Highlights anonymously in original high quality before they expire.",
    keywords: ["instagram","ig","story saver","instagram story download","save insta","storiesig","ig app","instagram story download app","instagram story saver","instagram story download apk","download ig story","story saver instagram","storiesig app","instagram story saver app","story saver app","download story ig private","best instagram story downloader","instagram story saver apk","story saver instagram app","story saver net","story saver apk","story saver instagram apk download","ig view","instagram story download 1080p","instagram stalker story viewer","instagram highlights download","instagram story download free app","cara download story ig orang lain","save instagram story with music","download highlight instagram"],
  },
  "instagram-photo-download": {
    slug: "instagram-photo-download",
    category: "photo",
    h1: "Instagram Photo & Carousel Downloader",
    metaTitle: "Instagram Photo & Carousel Downloader - Reelser",
    metaDescription: "Download Instagram pictures, photos, and carousel albums in original high-resolution JPG.",
    keywords: ["instagram","ig","save insta","m instagram","instagram photo download","instagram c","download instagram post","instagram picture download","save instagram posts","download post instagram","save instagram photos","instagram pic download","instagram post saver","ig photo download","instagram photo download full hd 1080p","download ins","download instagram carousel","download instagram post by link","download instagram post image","download instagram post online","download instagram post video","download instagram post with audio","download instagram post with link","download multiple instagram photos","download photo from instagram post","download post from instagram","download post instagram online","dredown download save instagram photos videos and multiple posts feed","ig photo downloader chrome","instagram album downloader"],
  },
  "download-instagram-post": {
    slug: "download-instagram-post",
    category: "photo",
    h1: "Instagram Photo & Carousel Downloader",
    metaTitle: "Instagram Photo & Carousel Downloader - Reelser",
    metaDescription: "Download Instagram pictures, photos, and carousel albums in original high-resolution JPG.",
    keywords: ["instagram","ig","save insta","m instagram","instagram photo download","instagram c","download instagram post","instagram picture download","save instagram posts","download post instagram","save instagram photos","instagram pic download","instagram post saver","ig photo download","instagram photo download full hd 1080p","download ins","download instagram carousel","download instagram post by link","download instagram post image","download instagram post online","download instagram post video","download instagram post with audio","download instagram post with link","download multiple instagram photos","download photo from instagram post","download post from instagram","download post instagram online","dredown download save instagram photos videos and multiple posts feed","ig photo downloader chrome","instagram album downloader"],
  },
  "instagram-carousel-download": {
    slug: "instagram-carousel-download",
    category: "photo",
    h1: "Instagram Photo & Carousel Downloader",
    metaTitle: "Instagram Photo & Carousel Downloader - Reelser",
    metaDescription: "Download Instagram pictures, photos, and carousel albums in original high-resolution JPG.",
    keywords: ["instagram","ig","save insta","m instagram","instagram photo download","instagram c","download instagram post","instagram picture download","save instagram posts","download post instagram","save instagram photos","instagram pic download","instagram post saver","ig photo download","instagram photo download full hd 1080p","download ins","download instagram carousel","download instagram post by link","download instagram post image","download instagram post online","download instagram post video","download instagram post with audio","download instagram post with link","download multiple instagram photos","download photo from instagram post","download post from instagram","download post instagram online","dredown download save instagram photos videos and multiple posts feed","ig photo downloader chrome","instagram album downloader"],
  },
  "instagram-dp-download": {
    slug: "instagram-dp-download",
    category: "profile",
    h1: "Instagram Profile Picture (DP) Downloader",
    metaTitle: "Instagram Profile Picture (DP) Downloader - Reelser",
    metaDescription: "View, zoom, and download any public Instagram avatar or profile picture (DP) in full resolution HD.",
    keywords: ["instagram","ig","instagram profile","instagram dp download","instagram profile picture viewer url","insta dp","instagram profile picture viewer","insta dp viewer","insta dp download","instagram pfp downloader","instagram profile picture download","insta dp viewer app","ig dp viewer","download instagram profile picture full size","full insta dp","hd insta dp","insta dp and story viewer","insta dp com","insta dp download hd","insta dp download online","insta dp download url","insta dp full","insta dp full size","insta dp hd","insta dp hd download","insta dp net","insta dp open","insta dp reels","insta dp reels download","insta dp save"],
  },
  "instagram-profile-picture-viewer": {
    slug: "instagram-profile-picture-viewer",
    category: "profile",
    h1: "Instagram Profile Picture (DP) Downloader",
    metaTitle: "Instagram Profile Picture (DP) Downloader - Reelser",
    metaDescription: "View, zoom, and download any public Instagram avatar or profile picture (DP) in full resolution HD.",
    keywords: ["instagram","ig","instagram profile","instagram dp download","instagram profile picture viewer url","insta dp","instagram profile picture viewer","insta dp viewer","insta dp download","instagram pfp downloader","instagram profile picture download","insta dp viewer app","ig dp viewer","download instagram profile picture full size","full insta dp","hd insta dp","insta dp and story viewer","insta dp com","insta dp download hd","insta dp download online","insta dp download url","insta dp full","insta dp full size","insta dp hd","insta dp hd download","insta dp net","insta dp open","insta dp reels","insta dp reels download","insta dp save"],
  },
  "instagram-audio-download": {
    slug: "instagram-audio-download",
    category: "audio",
    h1: "Instagram Audio & Reels MP3 Extractor",
    metaTitle: "Instagram Audio & Reels MP3 Extractor - Reelser",
    metaDescription: "Extract and download audio tracks, background music, and songs from Instagram Reels in high-quality MP3 format.",
    keywords: ["instagram","instagram music","m instagram","download reels","download reels with audio","download song from instagram","instagram mp3"],
  },
  "instagram-reels-song-download": {
    slug: "instagram-reels-song-download",
    category: "audio",
    h1: "Instagram Audio & Reels MP3 Extractor",
    metaTitle: "Instagram Audio & Reels MP3 Extractor - Reelser",
    metaDescription: "Extract and download audio tracks, background music, and songs from Instagram Reels in high-quality MP3 format.",
    keywords: ["instagram","instagram music","m instagram","download reels","download reels with audio","download song from instagram","instagram mp3"],
  },
  "saveinsta-alternative": {
    slug: "saveinsta-alternative",
    category: "reels",
    h1: "SaveInsta Alternative - Free Instagram Downloader",
    metaTitle: "SaveInsta Alternative - Free Instagram Downloader - Reelser",
    metaDescription: "The best SaveInsta alternative. Download Instagram Reels, Stories, Photos, and Videos in source quality.",
    keywords: ["save insta","saveinsta","save instagram reel to camera roll","app to save instagram videos","save instagram videos to camera roll","save instagram reels","saveinsta app","save instagram video to iphone","save instagram posts","save insta com","save instagram photos","save instagram video to phone","save insta net","save instagram story with music","save insta app","save instagram videos on iphone","save instagram reel without watermark","download and save instagram videos","dredown download save instagram photos videos and multiple posts feed","insave instagram","post save instagram","reel save instagram","save insta con","save insta download","save insta download reels","save insta dp","save insta hd","save insta reel video","save insta reels download","save insta story download"],
  },
  "ssinstagram-alternative": {
    slug: "ssinstagram-alternative",
    category: "reels",
    h1: "SSInstagram Alternative - Instagram Media Downloader",
    metaTitle: "SSInstagram Alternative - Instagram Media Downloader - Reelser",
    metaDescription: "Fastest SSInstagram alternative to download Instagram Reels, Stories, Photos, and Videos online.",
    keywords: ["instagram","instagram download","sssinstagram","instagram down","gram download","ssinstagram","sss instagram reels","instagram do","kate moss instagram","ss instagram reels download","ss instagram story download","ss instagram story download video","ss instagram video downloader","sss instagram download","sss instagram post","sss instagram reel download","sss instagram story","sss instagram story download","sss instagram story download video","sss instagram video","sss instagram video download without watermark","sss instagram without watermark","sssinstagram com id","sssinstagram post","sssinstagram stories","sssinstagram story download"],
  },
  "snapinsta-alternative": {
    slug: "snapinsta-alternative",
    category: "reels",
    h1: "SnapInsta Alternative - Fast Instagram Downloader",
    metaTitle: "SnapInsta Alternative - Fast Instagram Downloader - Reelser",
    metaDescription: "High-speed SnapInsta alternative. Save Instagram Reels, Videos, Stories, and DP in MP4/JPG.",
    keywords: ["snap insta","snap instagram","snap insta app","snapinsta download","snapinsta app download","download snap instagram","download snapinsta","https snapinsta app","insta video dow","instagram story download snapinsta","snap insta download","snap insta video download","snapinsta apk","snapinsta apk download","snapinsta app id","snapinsta app instagram downloader","snapinsta downloader","snapinsta instagram downloader","snapinsta story","snapinsta story download","snapinsta video download"],
  },
  "snaptik-instagram": {
    slug: "snaptik-instagram",
    category: "reels",
    h1: "Instagram Reels Downloader",
    metaTitle: "Instagram Reels Downloader - Reelser",
    metaDescription: "Download Instagram Reels in source quality MP4 with original crystal-clear audio. Fast, free, and no watermark.",
    keywords: ["instagram","ig","instagram reels download","reels download","save insta","reels downloader","download instagram reels","m instagram","for instagram","cara download reels ig","download reels instagram","download reels","instagram reels download app","reels video download","save instagram reels","app to download instagram reels","save reels ig","download ig reels","save reels to camera roll","download reels from instagram","instagram reels download apk","instagram reels video download","cara save reels ig","tiktok reels download","reels download app","save reels","download reels on instagram","instagram reels video download in gallery","save reels from instagram","apps to download instagram reels"],
  },
  "fastsave-instagram": {
    slug: "fastsave-instagram",
    category: "reels",
    h1: "Instagram Reels Downloader",
    metaTitle: "Instagram Reels Downloader - Reelser",
    metaDescription: "Download Instagram Reels in source quality MP4 with original crystal-clear audio. Fast, free, and no watermark.",
    keywords: ["instagram","ig","instagram reels download","reels download","save insta","reels downloader","download instagram reels","m instagram","for instagram","cara download reels ig","download reels instagram","download reels","instagram reels download app","reels video download","save instagram reels","app to download instagram reels","save reels ig","download ig reels","save reels to camera roll","download reels from instagram","instagram reels download apk","instagram reels video download","cara save reels ig","tiktok reels download","reels download app","save reels","download reels on instagram","instagram reels video download in gallery","save reels from instagram","apps to download instagram reels"],
  },
  "indown-alternative": {
    slug: "indown-alternative",
    category: "reels",
    h1: "Instagram Reels Downloader",
    metaTitle: "Instagram Reels Downloader - Reelser",
    metaDescription: "Download Instagram Reels in source quality MP4 with original crystal-clear audio. Fast, free, and no watermark.",
    keywords: ["instagram","ig","instagram reels download","reels download","save insta","reels downloader","download instagram reels","m instagram","for instagram","cara download reels ig","download reels instagram","download reels","instagram reels download app","reels video download","save instagram reels","app to download instagram reels","save reels ig","download ig reels","save reels to camera roll","download reels from instagram","instagram reels download apk","instagram reels video download","cara save reels ig","tiktok reels download","reels download app","save reels","download reels on instagram","instagram reels video download in gallery","save reels from instagram","apps to download instagram reels"],
  },
};
