import type { Locale } from "./i18n";
export const UI_TEXT: Record<Locale, Record<string, string>> = {
  "en": {
    "Search result": "Search result",
    "Zoom avatar": "Zoom avatar",
    "Open in Instagram": "Open in Instagram",
    "posts": "posts",
    "followers": "followers",
    "following": "following",
    "Downloading...": "Downloading...",
    "Download Profile DP (Original)": "Download Profile DP (Original)",
    "Show more": "Show more",
    "No posts available to display.": "No posts available to display.",
    "No Active Stories Right Now": "No Active Stories Right Now",
    "No stories were available from the source. They may have expired or could not be retrieved.": "No stories were available from the source. They may have expired or could not be retrieved.",
    "View Posts": "View Posts",
    "View Reels": "View Reels",
    "Story Highlights": "Story Highlights",
    "No highlights available to display.": "No highlights available to display.",
    "likes": "likes",
    "No reels available to display.": "No reels available to display.",
    "Profile picture": "Profile picture",
    "Close": "Close",
    "Highest resolution profile picture (Original)": "Highest resolution profile picture (Original)",
    "Ready for Download": "Ready for Download",
    "Source": "Source",
    "Available Downloads": "Available Downloads",
    "Service temporarily unavailable for maintenance.": "Service temporarily unavailable for maintenance.",
    "Free Instagram Downloader": "Free Instagram Downloader",
    "Download failed. Try again.": "Download failed. Try again.",
    "Free with usage limits to keep the service available.": "Free with usage limits to keep the service available.",
    "Zoom Avatar": "Zoom avatar",
    "Download Original Avatar": "Download Profile DP (Original)",
    "POSTS": "posts",
    "HIGHLIGHTS": "Story Highlights"
  },
  "ar": {
    "Search result": "نتيجة البحث",
    "Zoom avatar": "تكبير الصورة",
    "Open in Instagram": "فتح في إنستغرام",
    "posts": "منشورات",
    "followers": "متابعون",
    "following": "يتابع",
    "Downloading...": "جارٍ التحميل...",
    "Download Profile DP (Original)": "تحميل صورة الحساب",
    "Show more": "عرض المزيد",
    "No posts available to display.": "لا تتوفر منشورات للعرض حالياً.",
    "No Active Stories Right Now": "لا تتوفر قصص حالياً",
    "No stories were available from the source. They may have expired or could not be retrieved.": "تعذّر جلب القصص من المصدر. قد تكون انتهت صلاحيتها.",
    "View Posts": "عرض المنشورات",
    "View Reels": "عرض الريلز",
    "Story Highlights": "القصص المميزة",
    "No highlights available to display.": "لا تتوفر قصص مميزة للعرض.",
    "likes": "إعجابات",
    "No reels available to display.": "لا تتوفر مقاطع ريلز للعرض حالياً.",
    "Profile picture": "الصورة الشخصية",
    "Close": "إغلاق",
    "Highest resolution profile picture (Original)": "صورة الحساب بالجودة المتاحة",
    "Ready for Download": "متاح للتحميل",
    "Source": "المصدر",
    "Available Downloads": "التحميلات المتاحة",
    "Service temporarily unavailable for maintenance.": "الخدمة تحت الصيانة، حاول لاحقاً.",
    "Free Instagram Downloader": "أداة تحميل إنستغرام مجاناً",
    "Download failed. Try again.": "تعذّر التحميل. حاول مجدداً.",
    "Free with usage limits to keep the service available.": "مجاني مع حدود استخدام للحفاظ على توفر الخدمة.",
    "Zoom Avatar": "تكبير الصورة",
    "Download Original Avatar": "تحميل صورة الحساب",
    "POSTS": "منشورات",
    "HIGHLIGHTS": "القصص المميزة"
  },
  "es": {
    "Search result": "Resultado de búsqueda",
    "Zoom avatar": "Ampliar foto",
    "Open in Instagram": "Abrir en Instagram",
    "posts": "publicaciones",
    "followers": "seguidores",
    "following": "seguidos",
    "Downloading...": "Descargando...",
    "Download Profile DP (Original)": "Descargar foto de perfil",
    "Show more": "Mostrar más",
    "No posts available to display.": "No hay publicaciones disponibles.",
    "No Active Stories Right Now": "No hay historias disponibles",
    "No stories were available from the source. They may have expired or could not be retrieved.": "No se pudieron obtener las historias. Puede que hayan caducado.",
    "View Posts": "Ver publicaciones",
    "View Reels": "Ver Reels",
    "Story Highlights": "Historias destacadas",
    "No highlights available to display.": "No hay historias destacadas disponibles.",
    "likes": "Me gusta",
    "No reels available to display.": "No hay Reels disponibles.",
    "Profile picture": "Foto de perfil",
    "Close": "Cerrar",
    "Highest resolution profile picture (Original)": "Foto de perfil en la calidad disponible",
    "Ready for Download": "Listo para descargar",
    "Source": "Fuente",
    "Available Downloads": "Descargas disponibles",
    "Service temporarily unavailable for maintenance.": "Servicio en mantenimiento.",
    "Free Instagram Downloader": "Descargador gratuito de Instagram",
    "Download failed. Try again.": "No se pudo descargar. Inténtalo de nuevo.",
    "Free with usage limits to keep the service available.": "Gratis con límites de uso para mantener el servicio disponible.",
    "Zoom Avatar": "Ampliar foto",
    "Download Original Avatar": "Descargar foto de perfil",
    "POSTS": "publicaciones",
    "HIGHLIGHTS": "Historias destacadas"
  },
  "fr": {
    "Search result": "Résultat de recherche",
    "Zoom avatar": "Agrandir la photo",
    "Open in Instagram": "Ouvrir sur Instagram",
    "posts": "publications",
    "followers": "abonnés",
    "following": "abonnements",
    "Downloading...": "Téléchargement...",
    "Download Profile DP (Original)": "Télécharger la photo de profil",
    "Show more": "Afficher plus",
    "No posts available to display.": "Aucune publication disponible.",
    "No Active Stories Right Now": "Aucune story disponible",
    "No stories were available from the source. They may have expired or could not be retrieved.": "Les stories n’ont pas pu être récupérées. Elles ont peut-être expiré.",
    "View Posts": "Voir les publications",
    "View Reels": "Voir les Reels",
    "Story Highlights": "Stories à la une",
    "No highlights available to display.": "Aucune story à la une disponible.",
    "likes": "J’aime",
    "No reels available to display.": "Aucun Reel disponible.",
    "Profile picture": "Photo de profil",
    "Close": "Fermer",
    "Highest resolution profile picture (Original)": "Photo de profil dans la qualité disponible",
    "Ready for Download": "Prêt à télécharger",
    "Source": "Source",
    "Available Downloads": "Téléchargements disponibles",
    "Service temporarily unavailable for maintenance.": "Service en maintenance.",
    "Free Instagram Downloader": "Téléchargeur Instagram gratuit",
    "Download failed. Try again.": "Échec du téléchargement. Réessayez.",
    "Free with usage limits to keep the service available.": "Gratuit avec des limites pour préserver la disponibilité.",
    "Zoom Avatar": "Agrandir la photo",
    "Download Original Avatar": "Télécharger la photo de profil",
    "POSTS": "publications",
    "HIGHLIGHTS": "Stories à la une"
  },
  "pt": {
    "Search result": "Resultado da pesquisa",
    "Zoom avatar": "Ampliar foto",
    "Open in Instagram": "Abrir no Instagram",
    "posts": "publicações",
    "followers": "seguidores",
    "following": "seguindo",
    "Downloading...": "Baixando...",
    "Download Profile DP (Original)": "Baixar foto de perfil",
    "Show more": "Mostrar mais",
    "No posts available to display.": "Nenhuma publicação disponível.",
    "No Active Stories Right Now": "Nenhum story disponível",
    "No stories were available from the source. They may have expired or could not be retrieved.": "Não foi possível obter os stories. Eles podem ter expirado.",
    "View Posts": "Ver publicações",
    "View Reels": "Ver Reels",
    "Story Highlights": "Destaques",
    "No highlights available to display.": "Nenhum destaque disponível.",
    "likes": "curtidas",
    "No reels available to display.": "Nenhum Reel disponível.",
    "Profile picture": "Foto de perfil",
    "Close": "Fechar",
    "Highest resolution profile picture (Original)": "Foto de perfil na qualidade disponível",
    "Ready for Download": "Pronto para baixar",
    "Source": "Fonte",
    "Available Downloads": "Downloads disponíveis",
    "Service temporarily unavailable for maintenance.": "Serviço em manutenção.",
    "Free Instagram Downloader": "Downloader gratuito do Instagram",
    "Download failed. Try again.": "Falha no download. Tente novamente.",
    "Free with usage limits to keep the service available.": "Gratuito com limites de uso para manter o serviço disponível.",
    "Zoom Avatar": "Ampliar foto",
    "Download Original Avatar": "Baixar foto de perfil",
    "POSTS": "publicações",
    "HIGHLIGHTS": "Destaques"
  },
  "de": {
    "Search result": "Suchergebnis",
    "Zoom avatar": "Profilbild vergrößern",
    "Open in Instagram": "Auf Instagram öffnen",
    "posts": "Beiträge",
    "followers": "Follower",
    "following": "Gefolgt",
    "Downloading...": "Wird heruntergeladen...",
    "Download Profile DP (Original)": "Profilbild herunterladen",
    "Show more": "Mehr anzeigen",
    "No posts available to display.": "Keine Beiträge verfügbar.",
    "No Active Stories Right Now": "Keine Stories verfügbar",
    "No stories were available from the source. They may have expired or could not be retrieved.": "Stories konnten nicht abgerufen werden. Sie sind möglicherweise abgelaufen.",
    "View Posts": "Beiträge ansehen",
    "View Reels": "Reels ansehen",
    "Story Highlights": "Highlights",
    "No highlights available to display.": "Keine Highlights verfügbar.",
    "likes": "Gefällt mir",
    "No reels available to display.": "Keine Reels verfügbar.",
    "Profile picture": "Profilbild",
    "Close": "Schließen",
    "Highest resolution profile picture (Original)": "Profilbild in verfügbarer Qualität",
    "Ready for Download": "Bereit zum Herunterladen",
    "Source": "Quelle",
    "Available Downloads": "Verfügbare Downloads",
    "Service temporarily unavailable for maintenance.": "Dienst wird gewartet.",
    "Free Instagram Downloader": "Kostenloser Instagram-Downloader",
    "Download failed. Try again.": "Download fehlgeschlagen. Erneut versuchen.",
    "Free with usage limits to keep the service available.": "Kostenlos mit Nutzungslimits zur Sicherung der Verfügbarkeit.",
    "Zoom Avatar": "Profilbild vergrößern",
    "Download Original Avatar": "Profilbild herunterladen",
    "POSTS": "Beiträge",
    "HIGHLIGHTS": "Highlights"
  },
  "tr": {
    "Search result": "Arama sonucu",
    "Zoom avatar": "Fotoğrafı büyüt",
    "Open in Instagram": "Instagram’da aç",
    "posts": "gönderiler",
    "followers": "takipçiler",
    "following": "takip edilen",
    "Downloading...": "İndiriliyor...",
    "Download Profile DP (Original)": "Profil fotoğrafını indir",
    "Show more": "Daha fazla göster",
    "No posts available to display.": "Gösterilecek gönderi yok.",
    "No Active Stories Right Now": "Kullanılabilir hikâye yok",
    "No stories were available from the source. They may have expired or could not be retrieved.": "Hikâyeler alınamadı. Süreleri dolmuş olabilir.",
    "View Posts": "Gönderileri görüntüle",
    "View Reels": "Reels görüntüle",
    "Story Highlights": "Öne çıkanlar",
    "No highlights available to display.": "Öne çıkan hikâye yok.",
    "likes": "beğeni",
    "No reels available to display.": "Gösterilecek Reels yok.",
    "Profile picture": "Profil fotoğrafı",
    "Close": "Kapat",
    "Highest resolution profile picture (Original)": "Mevcut kalitede profil fotoğrafı",
    "Ready for Download": "İndirmeye hazır",
    "Source": "Kaynak",
    "Available Downloads": "Mevcut indirmeler",
    "Service temporarily unavailable for maintenance.": "Hizmet bakımda.",
    "Free Instagram Downloader": "Ücretsiz Instagram indirici",
    "Download failed. Try again.": "İndirme başarısız. Tekrar deneyin.",
    "Free with usage limits to keep the service available.": "Hizmetin kullanılabilirliği için kullanım sınırlarıyla ücretsiz.",
    "Zoom Avatar": "Fotoğrafı büyüt",
    "Download Original Avatar": "Profil fotoğrafını indir",
    "POSTS": "gönderiler",
    "HIGHLIGHTS": "Öne çıkanlar"
  },
  "id": {
    "Search result": "Hasil pencarian",
    "Zoom avatar": "Perbesar foto",
    "Open in Instagram": "Buka di Instagram",
    "posts": "postingan",
    "followers": "pengikut",
    "following": "mengikuti",
    "Downloading...": "Mengunduh...",
    "Download Profile DP (Original)": "Unduh foto profil",
    "Show more": "Tampilkan lainnya",
    "No posts available to display.": "Tidak ada postingan tersedia.",
    "No Active Stories Right Now": "Tidak ada cerita tersedia",
    "No stories were available from the source. They may have expired or could not be retrieved.": "Cerita tidak dapat diambil. Mungkin sudah kedaluwarsa.",
    "View Posts": "Lihat postingan",
    "View Reels": "Lihat Reels",
    "Story Highlights": "Sorotan cerita",
    "No highlights available to display.": "Tidak ada sorotan tersedia.",
    "likes": "suka",
    "No reels available to display.": "Tidak ada Reels tersedia.",
    "Profile picture": "Foto profil",
    "Close": "Tutup",
    "Highest resolution profile picture (Original)": "Foto profil dengan kualitas tersedia",
    "Ready for Download": "Siap diunduh",
    "Source": "Sumber",
    "Available Downloads": "Unduhan tersedia",
    "Service temporarily unavailable for maintenance.": "Layanan sedang dalam pemeliharaan.",
    "Free Instagram Downloader": "Pengunduh Instagram gratis",
    "Download failed. Try again.": "Unduhan gagal. Coba lagi.",
    "Free with usage limits to keep the service available.": "Gratis dengan batas penggunaan agar layanan tetap tersedia.",
    "Zoom Avatar": "Perbesar foto",
    "Download Original Avatar": "Unduh foto profil",
    "POSTS": "postingan",
    "HIGHLIGHTS": "Sorotan cerita"
  },
  "ru": {
    "Search result": "Результат поиска",
    "Zoom avatar": "Увеличить фото",
    "Open in Instagram": "Открыть в Instagram",
    "posts": "публикации",
    "followers": "подписчики",
    "following": "подписки",
    "Downloading...": "Загрузка...",
    "Download Profile DP (Original)": "Скачать фото профиля",
    "Show more": "Показать ещё",
    "No posts available to display.": "Нет доступных публикаций.",
    "No Active Stories Right Now": "Нет доступных историй",
    "No stories were available from the source. They may have expired or could not be retrieved.": "Не удалось получить истории. Возможно, срок их действия истёк.",
    "View Posts": "Смотреть публикации",
    "View Reels": "Смотреть Reels",
    "Story Highlights": "Актуальные истории",
    "No highlights available to display.": "Нет доступных актуальных историй.",
    "likes": "отметки «Нравится»",
    "No reels available to display.": "Нет доступных Reels.",
    "Profile picture": "Фото профиля",
    "Close": "Закрыть",
    "Highest resolution profile picture (Original)": "Фото профиля в доступном качестве",
    "Ready for Download": "Готово к скачиванию",
    "Source": "Источник",
    "Available Downloads": "Доступные загрузки",
    "Service temporarily unavailable for maintenance.": "Сервис на обслуживании.",
    "Free Instagram Downloader": "Бесплатное скачивание из Instagram",
    "Download failed. Try again.": "Не удалось скачать. Попробуйте снова.",
    "Free with usage limits to keep the service available.": "Бесплатно с ограничениями для поддержания доступности.",
    "Zoom Avatar": "Увеличить фото",
    "Download Original Avatar": "Скачать фото профиля",
    "POSTS": "публикации",
    "HIGHLIGHTS": "Актуальные истории"
  }
};
